[package]
name = "rust-miner"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
hex = "0.4"
num-bigint = "0.4"
bitcoin = "0.31"
secp256k1 = { version = "0.28", features = ["rand"] }
rand = "0.8"


